### ISSUE TITLE
Some hosts missing Elasticsearch23 AWS Plugin

### ISSUE THREAD

**Issue by kynetiv** [18F/kubernetes-broker#33]
Hi, I've created a number `elasticsearch23` service instances in GovCloud after PR #31 was merged in order to take advantage of the S3 snapshot utility. I noticed that some of the hosts don't appear to have been updated to reflect the added AWS Cloud plugin (or perhaps are having trouble installing the plugin).

Specifically, service instances on the `10.100.98.x` block don't have the plugin listed when i call:

`<svc_proxy>/_nodes/plugins`

However, when a service instance is created on `10.100.36.x`, this block does appear to have the AWS Cloud plugin available.

**Comment by cnelson** [comment]
Closing because ES23 is no longer offered
