### ISSUE TITLE
Elasticsearch17 service unresponsive

### ISSUE THREAD

**Issue by kynetiv** [18F/kubernetes-broker#43]
I'm trying to create an `elasticsearch17` service instance of plan `6x` on govcloud. The `cf` cli says that the service was created successfully, however, the ES node is completely unresponsive to any rest calls, curl eventually times out.

**Comment by jcscottiii** [comment]
@kynetiv we are deprecating `elasticsearch17` in GovCloud. We know that you are using 2.4 but were trying to use 1.7 for benchmarks for #34. The benchmarks given were good. Let us know if you really need 1.7 (I doubt it). Otherwise, I'll close this.

**Comment by jcscottiii** [comment]
replied. can close and move. (says I only have read only perms to this card??? )

**Comment by kynetiv** [comment]
That's fine. Ideally the baseline would be using the same stack but I'm sure we can make due. Thanks.
