### ISSUE TITLE
Evaluate bundled services

### ISSUE THREAD

**Issue by jmcarp** [18F/kubernetes-broker#7]
This broker comes with several [services](https://github.com/18F/kubernetes-broker/tree/master/catalogData), some of which rely on [custom images](https://github.com/18F/kubernetes-broker/tree/master/custom_images).
- Which services and plans should we offer to users?
- Are the bundled services adequate for our needs? We should vet the services that we plan to use.
- Are there services we want to add? Possibly newer versions of postgres, elasticsearch
- Is the service HA?
- Is the service secure?
- Initial sizes - small / med / large / xlarge
- Is the service backed up?

Initial Services
- [ ] Mysql
- [ ] ElasticSearch
- [ ] PostgreSQL
- [ ] MongoDB
- [ ] Redis

cc @sharms

**Comment by sharms** [comment]
Issue moved to [18F/cg-atlas #151](https://github.com/18F/cg-atlas/issues/151) via [**ZenHub**](https://www.zenhub.com/)
